---
# defaults file for host_hardening

# Manage the SSH daemon hardening [true | false]
host_hardening_sshd_manage: false
# Root login policy
# prohibit-password: root public-key access is supported.
# forced-commands-only: only for specialized root keys containing a command="..." restriction in authorized_keys.
# no: root login prohibit.
host_hardening_sshd_permit_root_login: "no"
# Maximum authentication attempts per connection
host_hardening_sshd_max_auth_tries: 3
# Time allowed to complete authentication
host_hardening_sshd_login_grace_time: 1m
# Allow this host to act as an SSH jump host using ProxyJump or ssh -J [true | false]
host_hardening_sshd_jump_host: false
# SSH cryptographic algorithm policy
# distribution: use distribution defaults
# remove: remove listed algorithms from distribution defaults
# replace: replace distribution defaults with the listed algorithms
# ['distribution' | 'remove' | 'replace']
host_hardening_sshd_algorithm_policy: 'distribution'
# SSH key-exchange algorithms
host_hardening_sshd_kex_algorithms: []
# SSH encryption algorithms
host_hardening_sshd_ciphers: []
# SSH message authentication algorithms
host_hardening_sshd_macs: []
# Server host-key signature algorithms
host_hardening_sshd_host_key_algorithms: []
# SSH user public-key signature algorithms
host_hardening_sshd_pubkey_accepted_algorithms: []


# region Debian based OS

# Uncomplicated Firewall
linux_security_ufw_default_list:
  - { direction: incoming, policy: deny }
  - { direction: outgoing, policy: allow }
linux_security_ufw_logging: 'on' # toggles logging. Logged packets use the LOG_KERN syslog facility [on, off, low, medium, high, full]

linux_security_ufw_rules_list:
  - rule: allow # add firewall rule [allow, deny, limit, reject]
    delete: 'no'  # delete rule [yes/no]
    direction: in  # select direction for a rule [in, incoming, out, outgoing, routed]
#    from_ip: 1.2.3.4 # source IP address
#    from_port: 12345  # source port
#    interface: eth0  # specify interface for the rule
#    log: 'yes'  # log new connections matched to this rule [yes/no]
    proto: tcp  # TCP/IP protocol [any, tcp, udp, ipv6, esp, ah, gre, igmp]
#    to_ip: 1.2.3.4  # destination IP address
    to_port: 22  # destination port
    comment: 'Allow SSH'

# endregion Debian based OS

# region RedHat based OS

# Firewalld service
# Ansible module documentation:
linux_security_firewalld_rules_list:
  - state: enabled # for service and ports [disabled, enabled] for zones [present, absent]
    # icmp_block: # icmp types to block "firewall-cmd --get-icmptypes"
    # icmp_block_inversion: # [Enable/Disable] inversion of ICMP blocks for a zone in firewalld
    # immediate: # [yes/no] should this configuration be applied immediately, if set as permanent (default no)
    # interface: # interface to add/remove to/from a zone
    # offline: # [yes/no] whether to run this module even when firewalld is offline.
    permanent: yes # [yes/no] should this configuration be in the running firewalld configuration or persist across reboots
    # port: # port or port range to add/remove to/from firewalld [PORT/PROTOCOL, PORT-PORT/PROTOCOL]
    # rich_rule: # rich rule to add/remove to/from firewalld https://firewalld.org/documentation/man-pages/firewalld.richlanguage.html
    service: ssh # service name to add/remove "firewall-cmd --get-services"
    # source: # source ip/network
    # target: # firewalld Zone target [default, ACCEPT, DROP, %%REJECT%%]
    # timeout: # the amount of time in seconds the rule should be in effect for when non-permanent
    zone: public # firewalld zone to add/remove to/from [block, dmz, drop, external, home, internal, public, trusted, work] (default public)

# endregion RedHat based OS
