---
# tasks file for configuring autoupdates

- name: Tasks on Debian/Ubuntu OS
  block:
    # https://wiki.debian.org/UnattendedUpgrades
    - name: Install Unattended Upgrades
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - unattended-upgrades
        - apt-listchanges

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#ansible-collections-ansible-builtin-template-module
    - name: Update Unattended Upgrades config files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
        backup: no
      loop:
        - { src: "apt-50unattended-upgrades-{{ ansible_distribution | lower }}.j2", dest: /etc/apt/apt.conf.d/50unattended-upgrades }
        - { src: apt-20auto-upgrades.j2, dest: /etc/apt/apt.conf.d/20auto-upgrades }

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#ansible-collections-ansible-builtin-file-module
    - name: Create Unattended Upgrades timer override directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /etc/systemd/system/apt-daily.timer.d
        - /etc/systemd/system/apt-daily-upgrade.timer.d
      notify: reload systemd

    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-list-of-hashes
    - name: Override Unattended Upgrades timer config
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - { src: apt-daily.timer.j2, dest: /etc/systemd/system/apt-daily.timer.d/override.conf }
        - { src: apt-daily-upgrade.timer.j2, dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf }
      notify: reload systemd
  when: ansible_os_family == 'Debian'

- name: Tasks on RedHat OS
  block:
    - name: Install dnf-automatic
      ansible.builtin.dnf:
        name: dnf-automatic
        state: present
        update_cache: yes

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#ansible-collections-ansible-builtin-file-module
    - name: Create dnf-autoupdate timer override directory
      ansible.builtin.file:
        path: /etc/systemd/system/dnf-automatic.timer.d
        state: directory
        owner: root
        group: root
        mode: '0755'
      notify: reload systemd

    - name: Update dnf-autoupdate config
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - { src: dnf-automatic.timer.j2, dest: /etc/systemd/system/dnf-automatic.timer.d/override.conf }
        - { src: dnf-automatic.conf.j2, dest: /etc/dnf/automatic.conf }
      notify: reload systemd

    - name: Enable dnf-automatic.timer
      ansible.builtin.systemd:
        name: dnf-automatic.timer
        state: started
        enabled: yes
  when: ansible_os_family == 'RedHat'
