---
# tasks for configuring ufw

- name: Tasks on Debian/Ubuntu OS
  block:
    # https://wiki.ubuntu.com/UncomplicatedFirewall
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Set ufw logging
      community.general.ufw:
        logging: "{{ linux_security_ufw_logging }}"
      when: linux_security_ufw_logging is defined

    # https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
    - name: Add ufw rules
      community.general.ufw:
        delete: "{{ item.delete | default(omit) }}"
        direction: "{{ item.direction }}"
        from_ip: "{{ item.from_ip | default(omit) }}"
        from_port: "{{ item.from_port | default(omit) }}"
        interface: "{{ item.interface | default(omit) }}"
        log: "{{ item.log | default(omit) }}"
        proto: "{{ item.proto }}"
        rule: "{{ item.rule }}"
        to_ip: "{{ item.to_ip | default(omit) }}"
        to_port: "{{ item.to_port }}"
        comment: "{{ item.comment | default(omit) }}"
      loop: "{{ linux_security_ufw_rules_list }}"
      when: linux_security_ufw_rules_list is defined
      notify:
        - reload ufw

    - name: Enable ufw
      community.general.ufw:
        state: enabled
  when: ansible_os_family == 'Debian'

- name: Tasks on RedHat OS
  block:
    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: present
        update_cache: yes

    # WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future releas
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
    - name: CentOS 8 disable AllowZoneDrifting
      ansible.builtin.lineinfile:
        path: /etc/firewalld/firewalld.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertbefore: "{{ item.insertbefore | default(omit) }}"
        owner: root
        group: root
        mode: '0644'
        create: yes
      loop:
        - regexp: '^#\s*Ansible'
          line: '# Ansible managed'
          insertbefore: BOF
        - regexp: '^AllowZoneDrifting='
          line: 'AllowZoneDrifting=no'
      when: ansible_distribution_version == "8"
      notify:
        - restart firewalld

    - name: Add firewalld rules
      ansible.posix.firewalld:
        icmp_block: "{{ item.icmp_block | default(omit) }}"
        icmp_block_inversion: "{{ item.icmp_block_inversion | default(omit) }}"
        immediate: "{{ item.immediate | default(omit) }}"
        interface: "{{ item.interface | default(omit) }}"
        offline: "{{ item.offline | default(omit) }}"
        permanent: "{{ item.permanent | default(omit) }}"
        port: "{{ item.port | default(omit) }}"
        rich_rule: "{{ item.rich_rule | default(omit) }}"
        service: "{{ item.service | default(omit) }}"
        source: "{{ item.source | default(omit) }}"
        state: "{{ item.state }}"
        target: "{{ item.target | default(omit) }}"
        timeout: "{{ item.timeout | default(omit) }}"
        zone: "{{ item.zone | default(omit) }}"
      loop: "{{ linux_security_firewalld_rules_list }}"
      when: linux_security_firewalld_rules_list is defined
  when: ansible_os_family == 'RedHat'
