---
- name: Manage local groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    gid: "{{ item.gid | default(omit) }}"
    system: "{{ item.system | default(false) }}"
  loop: "{{ access_management_groups_list_combined }}"
