---
# tasks file for access_management

- name: Apply access management
  tags:
  - access_management
  block:
    - name: Include OS-specific variables
      ansible.builtin.include_vars:
        file: "{{ ansible_facts['os_family'] | lower }}.yml"

    - name: Import ssh tasks
      ansible.builtin.import_tasks: ssh.yml

    - name: Import groups tasks
      ansible.builtin.import_tasks: groups.yml
      when: access_management_groups_list | length > 0
        or access_management_groups_list_append | length > 0

    - name: Import users tasks
      ansible.builtin.import_tasks: users.yml
      when: access_management_users_list | length > 0
        or access_management_users_list_append | length > 0

    - name: Import sudo tasks
      ansible.builtin.import_tasks: sudo.yml
