---
# - name: Tasks on RedHat OS
#   block:
#     - name: Install firewalld
#       ansible.builtin.dnf:
#         name: firewalld
#         state: present
#         update_cache: yes

#     # WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future releas
#     # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
#     - name: CentOS 8 disable AllowZoneDrifting
#       ansible.builtin.lineinfile:
#         path: /etc/firewalld/firewalld.conf
#         regexp: "{{ item.regexp }}"
#         line: "{{ item.line }}"
#         insertbefore: "{{ item.insertbefore | default(omit) }}"
#         owner: root
#         group: root
#         mode: '0644'
#         create: yes
#       loop:
#         - regexp: '^#\s*Ansible'
#           line: '# Ansible managed'
#           insertbefore: BOF
#         - regexp: '^AllowZoneDrifting='
#           line: 'AllowZoneDrifting=no'
#       when: ansible_distribution_version == "8"
#       notify:
#         - restart firewalld

#     - name: Add firewalld rules
#       ansible.posix.firewalld:
#         icmp_block: "{{ item.icmp_block | default(omit) }}"
#         icmp_block_inversion: "{{ item.icmp_block_inversion | default(omit) }}"
#         immediate: "{{ item.immediate | default(omit) }}"
#         interface: "{{ item.interface | default(omit) }}"
#         offline: "{{ item.offline | default(omit) }}"
#         permanent: "{{ item.permanent | default(omit) }}"
#         port: "{{ item.port | default(omit) }}"
#         rich_rule: "{{ item.rich_rule | default(omit) }}"
#         service: "{{ item.service | default(omit) }}"
#         source: "{{ item.source | default(omit) }}"
#         state: "{{ item.state }}"
#         target: "{{ item.target | default(omit) }}"
#         timeout: "{{ item.timeout | default(omit) }}"
#         zone: "{{ item.zone | default(omit) }}"
#       loop: "{{ linux_security_firewalld_rules_list }}"
#       when: linux_security_firewalld_rules_list is defined
#   when: ansible_os_family == 'RedHat'

- name: Manage Firewall settings on Debian
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['distribution'] == 'Debian'
  block:
    - name: Ensure nftables is installed
      ansible.builtin.apt:
        name: nftables
        state: present
        update_cache: true
        cache_valid_time: "{{ host_hardening_apt_cache_valid_time }}"

    - name: Configure nftables firewall
      when: host_hardening_firewall_enabled | bool
      ansible.builtin.template:
        src: nftables.conf.j2
        dest: "{{ host_hardening_firewall_nftables_config_file }}"
        owner: root
        group: root
        mode: '0755'
        validate: 'nft -c -f %s'
      notify: Reload nftables service

    - name: Enable and start nftables firewall service
      when: host_hardening_firewall_enabled | bool
      ansible.builtin.systemd_service:
        name: nftables.service
        state: started
        enabled: true

    - name: Disable and stop nftables firewall service
      when: not (host_hardening_firewall_enabled | bool)
      ansible.builtin.systemd_service:
        name: nftables.service
        state: stopped
        enabled: false

    - name: Disable nftables firewall check for active nftables tables
      when: not (host_hardening_firewall_enabled | bool)
      ansible.builtin.command:
        cmd: nft list tables
      register: host_hardening_firewall_nftables_tables
      changed_when: false
      check_mode: false

    - name: Disable nftables firewall flush active nftables rules
      ansible.builtin.command:
        cmd: nft flush ruleset
      changed_when: true
      when:
        - not (host_hardening_firewall_enabled | bool)
        - host_hardening_firewall_nftables_tables.stdout | trim | length > 0

- name: Manage Firewall settings on Ubuntu
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Ensure ufw is installed
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true
        cache_valid_time: "{{ host_hardening_apt_cache_valid_time }}"

    - name: Enable IPv6 support in ufw
      ansible.builtin.lineinfile:
        path: /etc/default/ufw
        regexp: '^IPV6='
        line: IPV6=yes
      notify: Reload ufw service

    - name: Set default ufw policy incoming
      when: host_hardening_firewall_enabled | bool
      community.general.ufw:
        default: "{{ 'reject' if host_hardening_firewall_default_incoming_policy == 'reject' else 'deny' }}"
        direction: incoming

    - name: Set default ufw policy outgoing
      when: host_hardening_firewall_enabled | bool
      community.general.ufw:
        default: allow
        direction: outgoing

    - name: Manage ufw rules
      when: host_hardening_firewall_enabled | bool
      community.general.ufw:
        rule: allow
        delete: "{{ item.state == 'absent' }}"
        direction: in
        proto: "{{ item.protocol }}"
        to_port: "{{ item.destination_port | string | replace('-', ':') }}"
        from_ip: "{{ item.source }}"
        comment: "Ansible managed: {{ item.name }}"
      loop: "{{ host_hardening_firewall_ingress_rules_list_combined }}"

    - name: Set ufw logging
      when: host_hardening_firewall_enabled | bool
      community.general.ufw:
        logging: "{{ 'on' if (host_hardening_firewall_logging | bool) else 'off' }}"

    - name: Enable ufw service
      when: host_hardening_firewall_enabled | bool
      community.general.ufw:
        state: enabled

    - name: Disable ufw service
      when: not (host_hardening_firewall_enabled | bool)
      community.general.ufw:
        state: disabled

- name: Manage Firewall settings on RedHat
  when:
    - ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Debug task
      ansible.builtin.debug:
        msg: RedHat distribution {{ ansible_facts['distribution'] }}
