---
# tasks file for host_hardening

- name: Apply host hardening
  tags:
    - host_hardening
  block:
    # - name: Validate system baseline configuration
    #   ansible.builtin.import_tasks: validate.yml

    - name: Include OS-specific variables
      ansible.builtin.include_vars:
        file: "{{ ansible_facts['os_family'] | lower }}.yml"

    - name: Import ssh tasks
      ansible.builtin.import_tasks: ssh.yml
      when: host_hardening_sshd_manage | bool

    # - name: Import firewall tasks
    #   ansible.builtin.import_tasks: "firewall.yml"
