---
- name: Apply sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state }}"
    sysctl_set: true
    reload: true
    sysctl_file: "{{ host_hardening_sysctl_params_file }}"
  loop: "{{ host_hardening_sysctl_params_list_combined }}"
  loop_control:
    label: "{{ item.name }}"
