---
# handlers file for system_baseline

- name: Restart NTP service
  ansible.builtin.systemd_service:
    state: restarted
    name: "{{ system_baseline_detected_ntp_service }}.service"

- name: Restart cron
  ansible.builtin.systemd_service:
    name: "{{ system_baseline_cron_service_name }}"
    state: restarted

- name: Restart postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes
