---
# handlers file for access_management

- name: Validate SSH daemon configuration
  ansible.builtin.command:
    cmd: /usr/sbin/sshd -t
  changed_when: false
  listen: Validate and reload SSH service

- name: Reload SSH service
  ansible.builtin.systemd_service:
    name: "{{ access_management_sshd_service_name }}"
    state: reloaded
  listen: Validate and reload SSH service
