---

- name: Setup docker on Debian OS
  block:
    # https://docs.docker.com/engine/install/
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - name: Install docker dependency
      ansible.builtin.apt:
        name: "{{ linux_docker_apt_dependency_package_list }}"
        state: present
        update_cache: yes

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
    - name: Add docker GPG key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html#ansible-collections-ansible-builtin-apt-repository-module
    - name: Add apt docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install docker engine on Debian/Ubuntu OS
      ansible.builtin.apt:
        name: "{{ linux_docker_package_list }}"
        state: present
        update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Setup docker on RedHat OS
  block:
    - name: Uninstall podman and it dependencies
      ansible.builtin.dnf:
        name: "{{ linux_docker_dnf_podman_remove_list }}"
        state: absent
        autoremove: yes

    - name: Add dnf docker repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install docker engine on RedHat OS
      ansible.builtin.dnf:
        name: "{{ linux_docker_package_list }}"
        state: present
        update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Start and enable docker service
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Download docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ linux_docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    checksum: "{{ linux_docker_compose_checksum }}"
    mode: '0755'

- name: Update docker daemon config file
  ansible.builtin.template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker
